import numpy as np
import pyfluids


DRY_AIR_MASS_FRACTIONS = {
    # generated by copilot, matches engineeringtoolbox.com data
    pyfluids.FluidsList.Nitrogen: 75.51760366879898,
    pyfluids.FluidsList.Oxygen: 23.139561050152018,
    pyfluids.FluidsList.Argon: 1.2881375564363484,
    pyfluids.FluidsList.CarbonDioxide: 0.05469772461264626,
}


def humidity_ratio_to_water_mass_fraction(humidity_ratio: float) -> float:
    return humidity_ratio / (1.0 + humidity_ratio)


def enforce_gas_phase(fluid):
    phases = getattr(pyfluids, "Phases", None)
    phase_gas = getattr(phases, "Gas", None) if phases is not None else None
    if phase_gas is None:
        return fluid

    fluid.specify_phase(phase_gas)
    return fluid


def make_humid_air_mixture(
    pressure: float,
    temp_rel: float,
    rel_humidity: float,
) -> pyfluids.Mixture:
    # get absolute mass humidity ratio using conditions w/ pyfluid humidair
    humidity_ratio = (
        pyfluids.HumidAir()
        .with_state(
            pyfluids.InputHumidAir.pressure(pressure),
            pyfluids.InputHumidAir.temperature(temp_rel),
            pyfluids.InputHumidAir.relative_humidity(rel_humidity),
        )
        .humidity
    )

    # use a mix of water and dry air
    water_mass_fraction = 100.0 * humidity_ratio_to_water_mass_fraction(humidity_ratio)
    dry_air_mass_fraction = 100.0 - water_mass_fraction

    # create a mixture using our dry air mix plus water vapor
    fluids = [*list(DRY_AIR_MASS_FRACTIONS.keys()), pyfluids.FluidsList.Water]
    fractions = [
        dry_air_mass_fraction * mass_fraction / 100.0
        for mass_fraction in DRY_AIR_MASS_FRACTIONS.values()
    ] + [water_mass_fraction]
    humid_air_mixture = pyfluids.Mixture(fluids, fractions)
    enforce_gas_phase(humid_air_mixture)

    return humid_air_mixture


def compute_compressor_outlet_state_isentropic(
    state_inlet: pyfluids.fluids.abstract_fluid.AbstractFluid,
    ratio_P: float,
) -> pyfluids.fluids.abstract_fluid.AbstractFluid:
    # compute the outlet state
    state_outlet = state_inlet.with_state(
        pyfluids.Input.pressure(
            ratio_P * state_inlet.pressure
        ),  # set by pressure ratio of the compressor
        pyfluids.Input.entropy(state_inlet.entropy),  # by isentropic compression assumption
    )

    return state_outlet


def compute_work_rate_isentropic(
    state_inlet,
    state_outlet,
    mass_flow_fluid=1.0,  # by default unity => returns unit-mass kJ/kg
):
    # work done by a system should be positive
    return mass_flow_fluid * (
        state_inlet.enthalpy / 1.0e3 - state_outlet.enthalpy / 1.0e3
    )  # kW = kJ/s


def compute_turbine_work_rate(
    state_inlet,
    state_outlet,
    mass_flow_fluid=1.0,
    isentropic_efficiency=1.0,
):
    work_rate_isentropic = compute_work_rate_isentropic(
        state_inlet,
        state_outlet,
        mass_flow_fluid=mass_flow_fluid,
    )
    return isentropic_efficiency * work_rate_isentropic  # kW = kJ/s


def compute_compressor_work_rate(
    state_inlet,
    state_outlet,
    mass_flow_fluid=1.0,  # by default unity, returns unit-mass kJ/kg
    isentropic_efficiency=1.0,
):
    work_rate_isentropic = compute_work_rate_isentropic(
        state_inlet,
        state_outlet,
        mass_flow_fluid=mass_flow_fluid,
    )
    return 1.0 / isentropic_efficiency * work_rate_isentropic  # kW


def compute_heat_transfer(
    state_inlet,
    state_outlet,
    mass_flow_fluid=1.0,  # by default unity, returns unit-mass kJ/kg
):
    # heat transfer to a system should be positive
    return mass_flow_fluid * (state_outlet.enthalpy / 1.0e3 - state_inlet.enthalpy / 1.0e3)  # kJ/s


def compute_turbine_outlet_state_isentropic(state_inlet, ratio_P):
    state_outlet = state_inlet.with_state(
        pyfluids.Input.pressure(
            state_inlet.pressure / ratio_P
        ),  # set by pressure ratio of the turbine
        pyfluids.Input.entropy(state_inlet.entropy),  # by isentropic expansion assumption
    )

    return state_outlet


class NGCTResult:
    closed: bool = True
    desc: str = ""
    mass_flowrate: np.ndarray  # kg/s
    states: dict[int, pyfluids.fluids.abstract_fluid.AbstractFluid]
    process_work_unit: dict[tuple[int, int], np.ndarray]
    process_heat_unit: dict[tuple[int, int], np.ndarray]
    state_names: dict[int, str]
    process_names: dict[tuple[int, int], str]

    def __init__(
        self,
        desc: str | None = None,
        closed: bool | None = None,
    ):
        if closed:
            self.closed = closed
        if desc:
            self.desc = desc

        self.mass_flowrate = None  # kg/s
        self.states = {}
        self.process_work_unit = {}
        self.process_heat_unit = {}
        self.state_names = {}
        self.process_names = {}

    def add_state(
        self,
        index: int,
        state: pyfluids.fluids.abstract_fluid.AbstractFluid,
        name: str,
    ):
        # validations
        if index in self.states:
            raise ValueError(f"index {index} already in states")
        if index in self.state_names:
            raise ValueError(f"index {index} already in states")

        # add the state
        self.states[index] = state
        self.state_names[index] = name

    def add_process(
        self,
        index_in: int,
        index_out: int,
        work_unit: np.ndarray,  # kJ/kg
        heat_unit: np.ndarray,  # kJ/kg
        name: str,
    ):
        process_index = (index_in, index_out)
        # validations
        if (index_in not in self.states) or (index_in not in self.state_names):
            raise ValueError(
                f"index {index_in} must be in states before process "
                f"({index_in}, {index_out}) can be added."
            )
        if (index_out not in self.states) or (index_out not in self.state_names):
            raise ValueError(
                f"index {index_out} must be in states before process "
                f"({index_in}, {index_out}) can be added."
            )
        if process_index in self.states:
            raise ValueError(f"process {process_index} already in states")
        if process_index in self.state_names:
            raise ValueError(f"process {process_index} already in states")

        # add the process
        self.process_work_unit[process_index] = work_unit
        self.process_heat_unit[process_index] = heat_unit
        self.process_names[process_index] = name

    def get_net_work(self):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        return mass_flowrate * sum(self.process_work_unit.values())  # kJ/s

    def get_net_heat_input(self):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        return mass_flowrate * sum(np.maximum(0.0, list(self.process_heat_unit.values())))  # kJ/s

    def get_net_heat_rejection(self):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        return mass_flowrate * sum(np.minimum(0.0, list(self.process_heat_unit.values())))  # kJ/s

    def get_back_work_ratio(self):
        back_work = -sum(np.minimum(0.0, list(self.process_work_unit.values())))  # kJ/s
        forward_work = sum(np.maximum(0.0, list(self.process_work_unit.values())))  # kJ/s
        return back_work / forward_work  # -

    def get_efficiency(self):
        net_work = self.get_net_work()  # kJ/kg
        net_heat_input = self.get_net_heat_input()  # kJ/kg
        return net_work / net_heat_input  # -

    def get_fuel_mass_flow(self, LHV_fuel, heating_process=(2, 3)):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        combustor_heat_input_rate = (
            mass_flowrate * self.process_heat_unit[heating_process]
        )  # [kg/s]*[kJ/kg] = kJ/s
        mass_flowrate_fuel = combustor_heat_input_rate / (1000.0 * LHV_fuel)  # [J/s]/[J/kg] = kg/s
        return mass_flowrate_fuel

    def get_fuel_air_ratio(self, LHV_fuel, heating_process=(2, 3)):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        mass_flowrate_fuel = self.get_fuel_mass_flow(LHV_fuel, heating_process=heating_process)
        return mass_flowrate_fuel / mass_flowrate

    def print_states(
        self,
    ):
        for idx_state, state in self.states.items():
            print(f"{(idx_state):>3d}:", end="")
            print(f" T={state.temperature:.2f}°C;", end="")
            print(f" h={state.enthalpy/1.0e3:.2f} MJ/kg;", end="")
            print(f" P={state.pressure/1.0e3:.2f} kPa;", end="")
            print()

    def __str__(self):
        output = f"\n{self.desc}\n" if self.desc else "\n"
        output += "states:\n"
        for idx_state, state in self.states.items():
            state_name = self.state_names.get(idx_state, "")
            output += (
                f"\t{idx_state} ({state_name}): T={state.temperature:.2f} C, "
                f"h={state.enthalpy/1.0e3:.2f} MJ/kg, P={state.pressure/1.0e3:.2f} kPa\n"
            )

        output += "\nprocesses:\n"
        for (idx_in, idx_out), work_unit in self.process_work_unit.items():
            heat_unit = self.process_heat_unit.get((idx_in, idx_out), 0.0)
            process_name = self.process_names.get((idx_in, idx_out), "")
            output += (
                f"\t{idx_in} -> {idx_out} ({process_name}): "
                f"W={work_unit:.2f} kJ/kg, Q={heat_unit:.2f} kJ/kg\n"
            )

        return output


class NGCT:
    """
    Thermodynamic model for the performance of a natural gas combustion turbine.

    Thermodynamic model for the performance of a specific natural gas combustion
    turbine. We assume a Brayton cycle with isentropic efficiency corrections
    for the compressor and turbine work. The turbine is assumed to ingest the
    intake fluid at maximum a specific volumetric flowrate. We also assume that
    the combustion chamber and turbine set the maximum designed firing
    temperature.
    """

    ratio_P: float  # -, pressure ratio
    Trel_firing: float  # deg C, relative temperature
    isentropic_efficiency_compressor: float  # -, compressor isentropic efficiency
    isentropic_efficiency_turbine: float  # -, turbine isentropic efficiency
    Q_fluid_max: float  # m**3/s, design volumetric flowrate

    design_conditions: dict  # design conditions dictionary

    def __init__(
        self,
        ratio_P: float,  # -, pressure ratio
        Trel_firing: float,  # deg C, relative temperature
        isentropic_efficiency_compressor: float,  # -, compressor isentropic efficiency
        isentropic_efficiency_turbine: float,  # -, turbine isentropic efficiency
        Q_fluid_max: float
        | None = None,  # m**3/s, design volumetric flowrate; unit-mass analysis if None
        design_conditions=None,  # dict, design conditions dictionary
    ):
        # set in variables
        self.ratio_P = ratio_P
        self.Trel_firing = Trel_firing
        self.isentropic_efficiency_compressor = isentropic_efficiency_compressor
        self.isentropic_efficiency_turbine = isentropic_efficiency_turbine
        self.Q_fluid_max = Q_fluid_max

        if design_conditions is not None:
            self.design_conditions = design_conditions

    def run_turbine_model(
        self,
        fluid_ambient_list: list[pyfluids.fluids.abstract_fluid.AbstractFluid]
        | pyfluids.fluids.abstract_fluid.AbstractFluid,
        power_rated: float = np.inf,  # kW, maximum rated power of the system
        heatrate_fuel_capacity: float = np.inf,  # kJ/s, maximum allowable heat rate
    ):
        singleton = False  # make a flag if there's just one ambient state to run
        if isinstance(
            fluid_ambient_list,
            pyfluids.fluids.abstract_fluid.AbstractFluid,
        ):
            fluid_ambient_list = [
                fluid_ambient_list,
            ]
            singleton = True

        results = []  # vector to store results for each ambient fluid state
        for fluid_ambient in fluid_ambient_list:  # loop over ambient fluid states
            ### CALCULATE THE CYCLE STATES
            # note: gas phase enforcement speeds up computation significantly

            enforce_gas_phase(fluid_ambient)  # ensure the ambient fluid is in the gas phase
            fluid_compressed = compute_compressor_outlet_state_isentropic(
                fluid_ambient,
                self.ratio_P,
            )  # after the compressor
            enforce_gas_phase(fluid_compressed)  # ensure the compressed fluid is in the gas phase
            fluid_combusted = fluid_compressed.with_state(
                pyfluids.Input.pressure(fluid_compressed.pressure),
                pyfluids.Input.temperature(self.Trel_firing),
            )  # after the combustion chamber
            enforce_gas_phase(fluid_combusted)  # ensure the combusted fluid is in the gas phase
            fluid_exhaust = compute_turbine_outlet_state_isentropic(
                fluid_combusted,
                self.ratio_P,
            )  # exhaust from the turbine
            enforce_gas_phase(fluid_exhaust)  # ensure the exhaust fluid is in the gas phase

            ### CALCULATE THE WORK INPUTS/OUTPUTS
            wdot_compressor = compute_compressor_work_rate(
                fluid_ambient,
                fluid_compressed,
                isentropic_efficiency=self.isentropic_efficiency_compressor,
            )  # now that the gas states are determined, compute the work
            wdot_turbine = compute_turbine_work_rate(
                fluid_combusted,
                fluid_exhaust,
                isentropic_efficiency=self.isentropic_efficiency_turbine,
            )  # now that the gas states are determined, compute the work

            ### CALCULATE THE HEAT INPUTS/OUTPUTS
            qdot_HX_combustor = compute_heat_transfer(
                fluid_compressed,
                fluid_combusted,
            )  # now that the gas states are determined, compute the heat transfer
            qdot_HX_exhaust_rejection = compute_heat_transfer(
                fluid_exhaust,
                fluid_ambient,
            )  # now that the gas states are determined, compute the heat transfer

            ### CALCULATE THE MASS FLOWRATE W/ CONTROL IF APPLICABLE
            mass_flowrate = (
                NGCT.get_mass_flowrate(
                    fluid_ambient,
                    self.Q_fluid_max,
                    wdot_turbine,
                    wdot_compressor,
                    qdot_HX_combustor,
                    power_rated=power_rated,
                    heatrate_fuel_capacity=heatrate_fuel_capacity,
                )
                if self.Q_fluid_max is not None
                else None
            )  # use static method

            ### PACK THE RESULT
            result = NGCTResult()

            # add mass flowrate
            result.mass_flowrate = mass_flowrate

            # add states
            result.add_state(1, fluid_ambient, "ambient intake air")
            result.add_state(2, fluid_compressed, "compressed air")
            result.add_state(3, fluid_combusted, "products of combustion")
            result.add_state(4, fluid_exhaust, "exhaust air")

            # add processes
            result.add_process(
                1,
                2,
                wdot_compressor,
                0.0,
                "isentropic compressor w/ work efficiency correction",
            )
            result.add_process(
                2,
                3,
                0.0,
                qdot_HX_combustor,
                "constant-pressure heating",
            )
            result.add_process(
                3,
                4,
                wdot_turbine,
                0.0,
                "isentropic turbine w/ work efficiency correction",
            )
            result.add_process(
                4,
                1,
                0.0,
                qdot_HX_exhaust_rejection,
                "constant-pressure (atmospheric) cooling",
            )

            # return logic
            if singleton:
                return result
            results.append(result)

        return results

    @staticmethod
    def celsius_to_kelvin(degC):
        return degC + 273.15  # K

    @staticmethod
    def kelvin_to_celsius(degK):
        return degK - 273.15  # C

    @staticmethod
    def get_mass_flowrate(
        fluid_ambient: pyfluids.fluids.abstract_fluid.AbstractFluid,
        Q_fluid_max: float,
        wdot_turbine: float,
        wdot_compressor: float,
        qdot_HX_combustor: float,
        power_rated: float = np.inf,
        heatrate_fuel_capacity: float = np.inf,
    ) -> float:
        """
        Calculate the mass flowrate constrained by design and operational limits.

        Determines the actual mass flowrate as the minimum of multiple limiting
        cases: volumetric flow capacity, power rating, and heat rate capacity.

        Args:
            fluid_ambient: Ambient fluid mixture with density property
                (pyfluids.fluids.abstract_fluid.AbstractFluid)
            Q_fluid_max: Maximum volumetric flowrate design limit (m**3/s)
            wdot_turbine: Turbine work output (kW/kg)
            wdot_compressor: Compressor work input (kW/kg)
            qdot_HX_combustor: Heat released by combustor (kW/kg)
            power_rated: Generator power rating constraint (kW), optional
            heatrate_fuel_capacity: Fuel heat capacity flow limit (kJ/s), optional

        Returns:
            Mass flowrate (kg/s) limited by the most restrictive constraint
        """
        # maximum mass flowrate allowed by the design
        mass_flowrate_max = fluid_ambient.density * Q_fluid_max  # kg/s
        # make a list of potential limiting cases
        mass_flowrate_candidates = [mass_flowrate_max]

        # throttle air/fuel flow to stay under given power rating (i.e. generator)
        mass_flowrate_candidates.append(
            power_rated / (wdot_turbine + wdot_compressor)  # kg/s <= [kW = kJ/s]/[kJ/kg]
        )

        # if flowrate is limited by a MMBtu/s (or kJ/s) flow limit
        mass_flowrate_candidates.append(
            heatrate_fuel_capacity / qdot_HX_combustor  # kg/s <= [kJ/s] / [kJ/kg]
        )

        # the actual mass flowrate is the minimum of the limiting cases
        return float(np.min(mass_flowrate_candidates))


class GE_7FA05_NGCT(NGCT):
    """
    Thermodynamic model for the GE 7FA.05 NGCT in simple-cycle performance.

    A thermodynamic model for the performance of the GE 7FA.05 natural gas
    combustion turbine in simple-cycle operation. We use a mix of fact- and
    data-sheet performance descriptions, textbook assumptions, and
    reverse-engineering to characterize the system. Reverse engineering targets
    matching the ISO performance at the design conditions.
    """

    def __init__(self):
        ratio_P = 18.712850988834695  # -, by reverse-engineering from datasheet
        Trel_firing = 1300.0  # °C, by textbook assumption
        isentropic_efficiency_compressor = 0.85  # -, by textbook assumption
        isentropic_efficiency_turbine = 0.90  # -, by textbook assumption
        Q_fluid = 477.78734437019483  # m**3/s, by reverse-engineering from datasheet datasheet

        design_conditions = {
            "P_ISO": 101325.0,  # Pa, ISO conditions
            "T_ISO": 288.15,  # K, ISO conditions
            "rel_humidity_ISO": 60.0,  # %, ISO conditions
            "eta_th_ISO": 0.385,  # -, from GEfactsheet for 7F.05
            "W_net_ISO": 239.0e3,  # kW, from GEfactsheet for 7F.05
        }

        # specialize the parent class
        super().__init__(
            ratio_P,
            Trel_firing,
            isentropic_efficiency_compressor,
            isentropic_efficiency_turbine,
            Q_fluid,
            design_conditions,
        )


class GE_7EA_NGCT_2014(NGCT):
    """
    Thermodynamic model for the GE 7EA NGCT in simple-cycle performance.

    A thermodynamic model for the performance of the GE 7EA natural gas
    combustion turbine in simple-cycle operation. We use a mix of fact- and
    data-sheet performance descriptions, textbook assumptions, and
    reverse-engineering to characterize the system. Reverse engineering targets
    matching the ISO performance at the design conditions.

    Matching is middling and the information on the turbine is very old.
    """

    def __init__(self):
        ratio_P = 12.6  # -, from NYISO GE factsheet
        Trel_firing = 1300.0  # °C, by textbook assumption
        isentropic_efficiency_compressor = 0.85  # -, by textbook assumption
        isentropic_efficiency_turbine = 0.90  # -, by textbook assumption
        Q_fluid = 238.3673469388  # m**3/s, from NYISO GE factsheet

        design_conditions = {
            "P_ISO": 101325.0,  # Pa, ISO conditions
            "T_ISO": 288.15,  # K, ISO conditions
            "rel_humidity_ISO": 60.0,  # %, ISO conditions
            "eta_th_ISO": 0.3275,  # -, from GEfactsheet for 7F.05
            "W_net_ISO": 85.4e3,  # kW, from GEfactsheet for 7F.05
        }

        # specialize the parent class
        super().__init__(
            ratio_P,
            Trel_firing,
            isentropic_efficiency_compressor,
            isentropic_efficiency_turbine,
            Q_fluid,
            design_conditions,
        )


if __name__ == "__main__":
    P_ambient = 101325.0  # Pa
    Trel_ambient = 15.0  # Pa
    rel_humidity_ambient = 60

    working_fluid = make_humid_air_mixture(P_ambient, Trel_ambient, rel_humidity_ambient)
    fluid_ambient = working_fluid.with_state(
        pyfluids.Input.pressure(P_ambient),
        pyfluids.Input.temperature(Trel_ambient),
    )

    ngct = GE_7EA_NGCT_2014()
    # ngct = GE_7FA05_NGCT()

    result = ngct.run_turbine_model(fluid_ambient)

    net_work = result.get_net_work()
    net_heat_input = result.get_net_heat_input()
    efficiency = net_work / net_heat_input
    exhaust_temperature = result.states[4].temperature

    print(f"net work: {net_work}")
    print(f"net heat input: {net_heat_input}")
    print(f"efficiency: {efficiency}")
    print(f"exhaust temperature: {exhaust_temperature}")
