import numpy as np
import pyfluids


DRY_AIR_MASS_FRACTIONS = {
    # generated by copilot, matches engineeringtoolbox.com data
    pyfluids.FluidsList.Nitrogen: 75.51760366879898,
    pyfluids.FluidsList.Oxygen: 23.139561050152018,
    pyfluids.FluidsList.Argon: 1.2881375564363484,
    pyfluids.FluidsList.CarbonDioxide: 0.05469772461264626,
}


def celsius_to_kelvin(degC):
    return degC + 273.15  # K


def kelvin_to_celsius(degK):
    return degK - 273.15  # C


def humidity_ratio_to_water_mass_fraction(humidity_ratio: float) -> float:
    return humidity_ratio / (1.0 + humidity_ratio)


def enforce_gas_phase(fluid):
    phases = getattr(pyfluids, "Phases", None)
    phase_gas = getattr(phases, "Gas", None) if phases is not None else None
    if phase_gas is None:
        return fluid

    fluid.specify_phase(phase_gas)
    return fluid


def make_humid_air_mixture(
    pressure: float,
    temp_rel: float,
    rel_humidity: float,
) -> pyfluids.Mixture:
    # get absolute mass humidity ratio using conditions w/ pyfluid humidair
    humidity_ratio = (
        pyfluids.HumidAir()
        .with_state(
            pyfluids.InputHumidAir.pressure(pressure),
            pyfluids.InputHumidAir.temperature(temp_rel),
            pyfluids.InputHumidAir.relative_humidity(rel_humidity),
        )
        .humidity
    )

    # use a mix of water and dry air
    water_mass_fraction = 100.0 * humidity_ratio_to_water_mass_fraction(humidity_ratio)
    dry_air_mass_fraction = 100.0 - water_mass_fraction

    # create a mixture using our dry air mix plus water vapor
    fluids = [*list(DRY_AIR_MASS_FRACTIONS.keys()), pyfluids.FluidsList.Water]
    fractions = [
        dry_air_mass_fraction * mass_fraction / 100.0
        for mass_fraction in DRY_AIR_MASS_FRACTIONS.values()
    ] + [water_mass_fraction]
    humid_air_mixture = pyfluids.Mixture(fluids, fractions)
    enforce_gas_phase(humid_air_mixture)

    return humid_air_mixture


def compute_isentropic_compression_outlet_state(
    state_inlet: pyfluids.fluids.abstract_fluid.AbstractFluid,
    ratio_P: float | None = None,
    ratio_compression: float | None = None,
) -> pyfluids.fluids.abstract_fluid.AbstractFluid:
    if not (ratio_P or ratio_compression) or (ratio_P and ratio_compression):
        raise ValueError(
            "compression process must specify exactly one of pressure or compression ratio"
        )
    # compute the outlet state
    state_outlet = state_inlet.with_state(
        (
            pyfluids.Input.pressure(ratio_P * state_inlet.pressure)
            if ratio_P
            else pyfluids.Input.specific_volume(
                1.0 / ratio_compression * state_inlet.specific_volume
            )
        ),  # set by pressure/compression ratio of the compressor
        pyfluids.Input.entropy(state_inlet.entropy),  # by isentropic compression assumption
    )

    return state_outlet


def compute_work_rate_isentropic(
    state_inlet,
    state_outlet,
    mass_flow_fluid=1.0,  # by default unity => returns unit-mass kJ/kg
):
    # work done by a system should be positive
    return mass_flow_fluid * (
        state_inlet.enthalpy / 1.0e3 - state_outlet.enthalpy / 1.0e3
    )  # kW = kJ/s


def compute_turbine_work_rate(
    state_inlet,
    state_outlet,
    mass_flow_fluid=1.0,
    isentropic_efficiency=1.0,
):
    work_rate_isentropic = compute_work_rate_isentropic(
        state_inlet,
        state_outlet,
        mass_flow_fluid=mass_flow_fluid,
    )
    return isentropic_efficiency * work_rate_isentropic  # kW = kJ/s


def compute_compressor_work_rate(
    state_inlet,
    state_outlet,
    mass_flow_fluid=1.0,  # by default unity, returns unit-mass kJ/kg
    isentropic_efficiency=1.0,
):
    work_rate_isentropic = compute_work_rate_isentropic(
        state_inlet,
        state_outlet,
        mass_flow_fluid=mass_flow_fluid,
    )
    return 1.0 / isentropic_efficiency * work_rate_isentropic  # kW


def compute_heat_transfer(
    state_inlet,
    state_outlet,
    mass_flow_fluid=1.0,  # by default unity, returns unit-mass kJ/kg
):
    # heat transfer to a system should be positive
    return mass_flow_fluid * (state_outlet.enthalpy / 1.0e3 - state_inlet.enthalpy / 1.0e3)  # kJ/s


def compute_isentropic_expansion_outlet_state(
    state_inlet,
    ratio_P: float | None = None,
    ratio_compression: float | None = None,
):
    if not (ratio_P or ratio_compression) or (ratio_P and ratio_compression):
        raise ValueError(
            "compression process must specify exactly one of pressure or compression ratio"
        )
    # compute the outlet state
    state_outlet = state_inlet.with_state(
        (
            pyfluids.Input.pressure(1.0 / ratio_P * state_inlet.pressure)
            if ratio_P
            else pyfluids.Input.specific_volume(ratio_compression * state_inlet.specific_volume)
        ),  # set by pressure/compression ratio of the turbine
        pyfluids.Input.entropy(state_inlet.entropy),  # by isentropic expansion assumption
    )

    return state_outlet


class ThermodynamicCycleResult:
    closed: bool = True
    desc: str = ""
    mass_flowrate: np.ndarray  # kg/s
    states: dict[int, pyfluids.fluids.abstract_fluid.AbstractFluid]
    process_work_unit: dict[tuple[int, int], np.ndarray]
    process_heat_unit: dict[tuple[int, int], np.ndarray]
    state_names: dict[int, str]
    process_names: dict[tuple[int, int], str]

    def __init__(
        self,
        desc: str | None = None,
        closed: bool | None = None,
    ):
        if closed:
            self.closed = closed
        if desc:
            self.desc = desc

        self.mass_flowrate = None  # kg/s
        self.states = {}
        self.process_work_unit = {}
        self.process_heat_unit = {}
        self.state_names = {}
        self.process_names = {}

    def add_state(
        self,
        index: int,
        state: pyfluids.fluids.abstract_fluid.AbstractFluid,
        name: str,
    ):
        # validations
        if index in self.states:
            raise ValueError(f"index {index} already in states")
        if index in self.state_names:
            raise ValueError(f"index {index} already in states")

        # add the state
        self.states[index] = state
        self.state_names[index] = name

    def add_process(
        self,
        index_in: int,
        index_out: int,
        work_unit: np.ndarray,  # kJ/kg
        heat_unit: np.ndarray,  # kJ/kg
        name: str,
    ):
        process_index = (index_in, index_out)
        # validations
        if (index_in not in self.states) or (index_in not in self.state_names):
            raise ValueError(
                f"index {index_in} must be in states before process "
                f"({index_in}, {index_out}) can be added."
            )
        if (index_out not in self.states) or (index_out not in self.state_names):
            raise ValueError(
                f"index {index_out} must be in states before process "
                f"({index_in}, {index_out}) can be added."
            )
        if process_index in self.states:
            raise ValueError(f"process {process_index} already in states")
        if process_index in self.state_names:
            raise ValueError(f"process {process_index} already in states")

        # add the process
        self.process_work_unit[process_index] = work_unit
        self.process_heat_unit[process_index] = heat_unit
        self.process_names[process_index] = name

    def get_net_work(self):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        return mass_flowrate * sum(self.process_work_unit.values())  # kJ/s

    def get_net_heat_input(self):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        return mass_flowrate * sum(np.maximum(0.0, list(self.process_heat_unit.values())))  # kJ/s

    def get_net_heat_rejection(self):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        return mass_flowrate * sum(np.minimum(0.0, list(self.process_heat_unit.values())))  # kJ/s

    def get_back_work_ratio(self):
        back_work = -sum(np.minimum(0.0, list(self.process_work_unit.values())))  # kJ/s
        forward_work = sum(np.maximum(0.0, list(self.process_work_unit.values())))  # kJ/s
        return back_work / forward_work  # -

    def get_efficiency(self):
        net_work = self.get_net_work()  # kJ/kg
        net_heat_input = self.get_net_heat_input()  # kJ/kg
        return net_work / net_heat_input  # -

    def get_fuel_mass_flow(self, LHV_fuel, heating_process=(2, 3)):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        combustor_heat_input_rate = (
            mass_flowrate * self.process_heat_unit[heating_process]
        )  # [kg/s]*[kJ/kg] = kJ/s
        mass_flowrate_fuel = combustor_heat_input_rate / (1000.0 * LHV_fuel)  # [J/s]/[J/kg] = kg/s
        return mass_flowrate_fuel

    def get_fuel_air_ratio(self, LHV_fuel, heating_process=(2, 3)):
        mass_flowrate = self.mass_flowrate if self.mass_flowrate else 1.0
        mass_flowrate_fuel = self.get_fuel_mass_flow(LHV_fuel, heating_process=heating_process)
        return mass_flowrate_fuel / mass_flowrate

    def print_states(
        self,
    ):
        for idx_state, state in self.states.items():
            print(f"{(idx_state):>3d}:", end="")
            print(f" T={state.temperature:.2f}°C;", end="")
            print(f" h={state.enthalpy/1.0e3:.2f} MJ/kg;", end="")
            print(f" P={state.pressure/1.0e3:.2f} kPa;", end="")
            print(f" rho={state.density:.2f} kg/m**3;", end="")
            print()

    def __str__(self):
        output = f"\n{self.desc}\n" if self.desc else "\n"
        output += "states:\n"
        for idx_state, state in self.states.items():
            state_name = self.state_names.get(idx_state, "")
            output += (
                f"\t{idx_state} ({state_name}): "
                f"T={state.temperature:.2f} C ({celsius_to_kelvin(state.temperature):.2f} K), "
                f"h={state.enthalpy/1.0e3:.2f} MJ/kg, "
                f"P={state.pressure/1.0e3:.2f} kPa\n"
                f"rho={state.density:.2f} kg/m**3\n"
            )

        if len(self.process_names):
            output += "\nprocesses:\n"
            for (idx_in, idx_out), work_unit in self.process_work_unit.items():
                heat_unit = self.process_heat_unit.get((idx_in, idx_out), 0.0)
                process_name = self.process_names.get((idx_in, idx_out), "")
                output += (
                    f"\t{idx_in} -> {idx_out} ({process_name}): "
                    f"W={work_unit:.2f} kJ/kg, Q={heat_unit:.2f} kJ/kg\n"
                )

        return output
